### ISSUE TITLE
form ProjectForm needs updating.

### ISSUE THREAD

**Issue by dangeratio** [wildfish/cookiecutter-django-crud#9]
Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form ProjectForm needs updating.

I get the above error running localhost:8000/projects/  after using cookiecutter on projects app with this model:

    from django.db import models
    from django.contrib.auth.models import User
    class Project(models.Model):
        class Meta:
            db_table = 'projects'
        title = models.CharField(max_length=200)
        detail = models.TextField()
        key_title = models.CharField(max_length=5)
        owner = models.ForeignKey(User, db_column='username')

**Comment by rolo** [comment]
Ah yes, you're quite right. This is required since Django 1.8. I'll add some code to generate an automatic Meta fields attribute to cover the default case.

In your case, you should open your forms.py and add a `fields` attribute to your model form. So it would look something like this:

```
class ProjectForm(models.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'detail', 'key_title', 'owner', )  # add whichever fields you want here
```

You can read more about this here, https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#modelform

Thanks for reporting this.

As an aside, if there's not a particular reason for specifying them, you can omit the `db_table` and `db_column` params. It's typical to let Django pick them for you (just ignore me if you knew this already).
